FROM python:3.12-slim

# Instalación de dependencias
RUN apt-get update && \
    apt-get install -y curl git unzip libstdc++6 ca-certificates procps && \
    rm -rf /var/lib/apt/lists/*

# Instalar Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Agrega Ollama al PATH
ENV PATH="/root/.ollama/bin:${PATH}"

# Precrear el directorio del modelo (esto ayuda a preservar el modelo luego del pull)
RUN mkdir -p /root/.ollama

# Crear directorio de trabajo
WORKDIR /app

# Instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir ollama && \
    pip install --no-cache-dir -r requirements.txt

# Copiar aplicación
COPY ./PaperHound .

# Descargar modelo en el build usando servidor temporal
RUN bash -c "\
    ollama serve & \
    sleep 5 && \
    curl -s http://localhost:11434/ > /dev/null && \
    ollama pull deepseek-r1:8b && \
    pkill ollama"

# Exponer puertos
EXPOSE 3000
EXPOSE 11434

# Script de arranque
CMD ["bash", "/app/start.sh"]
